version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgress
      - DB_NAME=books_tracking
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=books_tracking
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
